<project xmlns="http://maven.apache.org/POM/4.0.0">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.example</groupId>
    <artifactId>calculator</artifactId>
    <version>1.0</version>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.18</version>
    </parent>

    <properties>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>test_artifact</id>
            <url>https://pkgs.dev.azure.com/wy220506/wy220506/_packaging/test_artifact/maven/v1</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <distributionManagement>
        <repository>
            <id>test_artifact</id>
            <name>Azure Artifacts Release Repository</name>
            <url>https://pkgs.dev.azure.com/wy220506/wy220506/_packaging/test_artifact/maven/v1</url>
        </repository>
        <snapshotRepository>
            <id>test_artifact</id>
            <name>Azure Artifacts Snapshot Repository</name>
            <url>https://pkgs.dev.azure.com/wy220506/wy220506/_packaging/test_artifact/maven/v1</url>
        </snapshotRepository>
    </distributionManagement>

    <build>
        <plugins>

            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>

        </plugins>
    </build>

</project>
